### ISSUE TITLE
Adding r-rmatio to conda-forge

### ISSUE THREAD

**Issue by trangdata** [stewid/rmatio#13]
Wonderful package, @stewid!!! 🚀 

Would be great if r-rmatio could be made available on the [conda-forge](https://anaconda.org/conda-forge) channel. Many of us use this for software development and create reproducible workflows. I know r-rmatio's currently on the [r channel](https://anaconda.org/r/r-rmatio) but I'm having a lot of trouble building an image with it because of conflicts. Let me know what you think! Thank you!!!

**Comment by stewid** [comment]
Thanks.

I do not use conda-forge myself so I have no experience of how it works. But if you want to add and maintain rmatio there, I think it sounds like a good idea. Looks like it's an old version of rmatio (0.14) available on the r-channel. Is that why it does not work?

**Comment by trangdata** [comment]
I'm happy to take a stab at [this](https://conda-forge.org/docs/maintainer/adding_pkgs.html). Seems straightforward enough! I'll keep you updated with the progress. Right now, my `conda update conda` is [taking forever](https://github.com/conda/conda/issues/7938).

**Comment by trangdata** [comment]
Hi @stewid  all checks on the PR have passed. When you have a chance could you let me know if you'd like to be listed as a recipe maintainer, please? 🙏🏽  Thanks a ton!

**Comment by stewid** [comment]
Hi @trangdata No, I don't want to be listed as a recipe maintainer since I do not use conda-forge myself and I have no experience of how it works.
Thanks

**Comment by trangdata** [comment]
PR has been merged. rmatio is now on conda-forge: https://anaconda.org/conda-forge/r-rmatio
